name: CI for Terraform modules
on:
  workflow_call:
    inputs:
      path:
        description: "The path to the Terraform module"
        required: false
        type: string
        default: ""
      terraform_version:
        description: "The Terraform version"
        required: false
        type: string
        default: "1.1.0"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - run: terraform fmt -check
        working-directory: ${{ inputs.path }}

      - run: terraform init -backend=false
        working-directory: ${{ inputs.path }}

      - run: terraform validate
        working-directory: ${{ inputs.path }}
